# Generated by Django 4.2.6 on 2024-01-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0005_remove_profile_following_stream_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
