# Generated by Django 4.2.6 on 2024-01-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0007_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
    ]
