# Generated by Django 4.2.6 on 2024-01-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0008_remove_profile_location_remove_profile_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
