# Generated by Django 4.2.6 on 2024-01-26 06:43

import Social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0011_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to=Social.models.user_directory_path),
        ),
    ]
