# Generated by Django 4.2.6 on 2024-01-26 06:45

import Social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0012_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=Social.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Social.models.user_directory_path),
        ),
    ]
