# Generated by Django 4.2.6 on 2024-01-28 10:08

import Social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0013_alter_post_picture_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default="{% static 'images/dpplaceholder.png' %}", null=True, upload_to=Social.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
