# Generated by Django 4.2.6 on 2024-02-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0016_screentime'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentime',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
