# Generated by Django 4.2.6 on 2024-02-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0017_screentime_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentime',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
