# Generated by Django 4.2.6 on 2024-02-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0018_screentime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screentime',
            name='time',
        ),
    ]
