# Generated by Django 4.2.6 on 2024-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0019_remove_screentime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screentime',
            name='date',
        ),
        migrations.AddField(
            model_name='screentime',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
