# Generated by Django 4.2.6 on 2024-02-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0020_remove_screentime_date_screentime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screentime',
            name='time',
        ),
        migrations.AddField(
            model_name='screentime',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
