# Generated by Django 4.2.6 on 2024-02-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0025_notifications_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Social.post'),
        ),
    ]
