# Generated by Django 4.2.6 on 2024-03-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0029_alter_notification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='Social.profile'),
        ),
    ]
