# Generated by Django 4.2.6 on 2024-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0030_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
